---
title: "Untitled"
format: html
---
```{r}
library(scan)
library(gt)
apa_style <- function(gt_tbl) {
  gt_tbl  |> 
    tab_options(
      table.border.bottom.color = "white",
      #table.border.bottom.width = 3,
      
      table.border.top.color = "white",
      #table.border.top.width = 3,
      
      table_body.border.bottom.color = "black",
      table_body.border.bottom.width = 3,
      
      table_body.border.top.color = "black",
      table_body.border.top.width = 3,
      
      table_body.hlines.width = 0,
      
      heading.border.bottom.width = 3,
      heading.border.bottom.color = "black",
      heading.title.font.size = "100%",
      column_labels.border.bottom.width = 2,
      column_labels.border.bottom.color = "black"
    )  |> 
    opt_table_font(font = "times") |> 
    gt::cols_align(align = "center") |> 
    gt::cols_align(align = "left", columns = 1)
}

```
```{r}
res <- exampleAB |> overlap() 
note <- "PND = Percentage Non-Overlapping Data; PEM = Percentage Exceeding the Median; PET = Percentage Exceeding the Trend; NAP = Nonoverlap of all pairs; NAP-R = NAP rescaled; PAND = Percentage all nonoverlapping data; IRD = Improvement rate difference; Tau U (A + B - trend A) = Parker's Tau-U; Tau U (A + B - trend A + trend B) = Parker's Tau-U; Base Tau = Baseline corrected Tau; Delta M = Mean difference between phases; Delta Trend = Trend difference between phases; SMD = Standardized Mean Difference; Hedges g = Corrected SMD."

caption <- "Overlap indices. Comparing phase 1 against phase 2"
```

```{r}
res |> 
  export(footnote ="") |> 
  kableExtra::footnote(note ,footnote_as_chunk = FALSE)
```

```{r}
res$overlap |> 
  knitr::kable("html") |> 
  kableExtra::footnote(general = note)

```

```{r}
res$overlap |> 
  gt() |> 
  tab_header(md(caption)) |> 
  opt_align_table_header(align = "left") |> 
  fmt_number() |> 
  apa_style() |> 
  tab_footnote(md(paste0("*Note:*<br> ", note)))
```

